### ISSUE TITLE
Need Update

### ISSUE THREAD

**Issue by jimzijun** [maleblond/angular-fusejs#7]
Need Update
FuseOption<T> need a type

**Comment by joarkm** [comment]
I think this is the error @zyi103 refers to:

```typescript
ERROR in node_modules/angular-fusejs/src/fusejs.service.d.ts:3:47 - error TS2314: Generic type 'FuseOptions<T>' requires 1 type argument(s).

export interface AngularFusejsOptions extends FuseOptions {
                                              ~~~~~~~~~~~
```

**Comment by RogierVC** [comment]
+1

**Comment by almothafar** [comment]
You may need to see my fork, let me know if that works for you 
https://github.com/almothafar/angular-fusejs

**Comment by Rouvas** [comment]
> You may need to see my fork, let me know if that works for you https://github.com/almothafar/angular-fusejs

Greetings. Unfortunately, it did not work on version 12.0.5. I get an error that the minimum version of Angular to run is 14

**Comment by almothafar** [comment]
Strange, if you check the code it requires 12 and above, anyway if you are
in Angular 12 version 1.1.0 should be working fine.

But still I'm not sure what kind of errors you have, it should not be
happening as peer dependencies is >=12
